### ISSUE TITLE
fatal runtime error: failed to initiate panic, error 5

### ISSUE THREAD

**Issue by basilgeorge** [snipsco/snips-nlu#563] opened 2018-04-16 04:48 UTC
I am getting this error when trying to train the engine:

thread '<unnamed>' panicked at 'No such local time', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.3.0/src/offset/mod.rs:151:34
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

When run with RUST_BACKTRACE=1, this is the error log:

thread '<unnamed>' panicked at 'No such local time', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.3.0/src/offset/mod.rs:151:34
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp ::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: <chrono::offset::LocalResult<T>>::unwrap
   7: <rustling_ontology_moment::Moment<T>>::add_months
   8: <rustling_ontology_moment::Moment<T> as core::ops::arith::Add<rustling_ontology_moment::period::PeriodComp>>::add
   9: <rustling_ontology_moment::Interval<T> as core::ops::arith::Add<&'a rustling_ontology_moment::period::Period>>::add
  10: <rustling_ontology_moment::interval_constraints::ShiftBy<T> as rustling_ontology_moment::interval_constraints::IntervalConstraint<T>>::to_walker::{{closure}}
  11: <rustling_ontology_moment::interval_constraints::Translate<T> as rustling_ontology_moment::interval_constraints::IntervalConstraint<T>>::to_walker::{{closure}}
  12: <rustling_ontology_moment::walker::Walker<V>>::next
  13: <rustling_ontology_moment::walker::Walker<V>>::next
  14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  15: <rustling_ontology_moment::interval_constraints::Translate<T> as rustling_ontology_moment::interval_constraints::IntervalConstraint<T>>::to_walker
  16: <rustling_ontology_moment::interval_constraints::ShiftBy<T> as rustling_ontology_moment::interval_constraints::IntervalConstraint<T>>::to_walker
  17: <rustling_ontology_values::context::ResolverContext as rustling_ontology_values::context::ParsingContext<rustling_ontology_values::dimension::Dimension>>::resolve
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  20: <rustling_ontology::tagger::CandidateTagger<'a, C> as rustling::MaxElementTagger<rustling_ontology_values::dimension::Dimension>>::tag
  21: <rustling::Parser<V, Feat, Extractor>>::candidates
  22: <rustling::Parser<V, Feat, Extractor>>::parse
  23: rustling_ontology::Parser::parse
  24: snips_nlu_ontology::builtin_entities::builtin_entity_parser::BuiltinEntityParser::extract_entities
  25: snips_nlu_ontology_ffi::builtin_entity_parser::extract_entity
  26: nlu_ontology_extract_entities_json
  27: ffi_nlu_ontology_extract_entities_json
  28: ffi_call_unix64
  29: ffi_call
  30: _ctypes_callproc
  31: <unknown>
  32: PyEval_EvalFrameEx
  33: PyEval_EvalCodeEx
  34: PyEval_EvalFrameEx
  35: PyEval_EvalCodeEx
  36: PyEval_EvalFrameEx
  37: PyEval_EvalCodeEx
  38: PyEval_EvalFrameEx
  39: PyEval_EvalCodeEx
  40: PyEval_EvalFrameEx
  41: PyEval_EvalCodeEx
  42: PyEval_EvalFrameEx
  43: PyEval_EvalCodeEx
  44: PyEval_EvalFrameEx
  45: PyEval_EvalCodeEx
  46: PyEval_EvalFrameEx
  47: PyEval_EvalCodeEx
  48: <unknown>
  49: PyRun_FileExFlags
  50: PyRun_SimpleFileExFlags
  51: Py_Main
  52: __libc_start_main
  53: _start
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

I am running this on Ubuntu 16.04 LTS system, after installing snips-nlu from the repository (pip install snips-nlu). The config file used to initialize the engine is "config_en.json", obtained directly from git.

Can someone help?
Thanks.

**Comment by adrienball** [comment] 2018-04-16 09:54
Hi @basilgeorge, thanks for reporting this issue, would be it possible for you to provide the dataset that you are using for training? It would help a lot.
Apparently some date in your dataset is causing the crash, so if you manage to isolate one faulty utterance, that would probably be enough to investigate.
Thank you

**Comment by basilgeorge** [comment] 2018-04-16 11:34
Hi @adrienball, thanks for the reply. I have isolated four utterances which are causing the problem:

The team of scientists say the moon 's thick nitrogen and methane atmosphere is possibly undergoing chemical reactions similar to those that unfolded on [GEO:GEO](Earth) billions years ago .

but after the ice ages , high mountains of [GPE:GPE](taiwan) which were squeezed up from edges two tectonic plates a million years ago became their refuge .

The titanosaurs were plant-eating dinosaurs , called sauropods that lived more than 100 million years ago .

The [GEO:GEO](U.S.) space agency [ORG:ORG](NASA) said Tuesday that the farthest galaxies in snapshot are seen as they appeared more than 13 billion years ago , or roughly 650 million after [ORG:ORG](Big) [ORG:ORG](Bang) [ORG:ORG](-) massive explosion many scientists believe formed our universe .

All sentences having "million years ago" or "billion years ago" in them seem to cause the error. By removing these lines, the training gets completed most of the times, although occasionally the same "failed to initiate panic" errors occurs.  

Thanks.

**Comment by adrienball** [comment] 2018-04-16 12:58
What's happening here is that our builtin entity extractor captures some dates in your data, like `million years ago`, and crashes in the process of resolving them because the datetime dependency that we used, [chrono](https://github.com/chronotope/chrono), do not support dates that are too far away.
This is definitely a bug, the expected behavior is to return no dates instead of crashing.
We will address this in the upcoming releases.

At the moment, the only workaround for you is to remove all dates similar to `million years ago`, like you did.
Thanks!

**Comment by basilgeorge** [comment] 2018-04-16 13:12
Thanks @adrienball. Hope the bug would be fixed soon.

**Comment by adrienball** [comment] 2018-04-24 10:01
Hi @basilgeorge,
This issue should be fixed in the release `0.13.3`.
Could you please confirm that everything is working on your side with this new version?
Thanks!

**Comment by basilgeorge** [comment] 2018-04-24 14:49
Hi @adrienball, the issue has been fixed. Thanks!

**Closed** 2018-04-24 14:51 UTC
