### ISSUE TITLE
thread '<unnamed>' panicked at 'No such local time', /Users/toborspins/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.6/src/offset/mod.rs:145:34 note: Run with `RUST_BACKTRACE=1` for a backtrace. fatal runtime error: failed to initiate panic, error 5

### ISSUE THREAD

**Issue by POMCP** [snipsco/snips-nlu#683] opened 2018-10-17 11:12 UTC
Hello I see there was a similar issue being opened previously. This is however still happening. Is there a fix expected?

I am using python 3 on MacBook Pro.

**Comment by adrienball** [comment] 2018-10-22 07:37
Hey @POMCP ,
Thanks for reporting this issue.
To debug it, I would need to know the following:
- is this happening during training or parsing ?
- in which language ?
- could you manage to find a faulty utterance causing the bug, and sharing it here ?

Cheers,
Adrien

**Comment by adrienball** [comment] 2019-02-05 08:49
Hi @nicomitchell, I can indeed reproduce the crash with this example.
Thanks, I will investigate.

**Comment by nicomitchell** [comment] 2019-02-05 15:32
To add, if I get rid of the '(ENDS 9/31)' part in the string, it runs fine. So it seems to be tied to the date.

**Comment by adrienball** [comment] 2019-02-05 15:39
Yep, the bug was identified and a fix has been made here --> https://github.com/snipsco/rustling-ontology/pull/159/files

**Comment by adrienball** [comment] 2019-03-07 09:26
@POMCP @nicomitchell
The bug should be fixed in the latest release (0.19.4).
I'm closing this issue, feel free to re-open if it is still there.

**Closed by adrienball** 2019-03-07 09:26 UTC
