### ISSUE TITLE
Probability greatly diminished when colliding intent utterances

### ISSUE THREAD

**Issue by warent** [snipsco/snips-nlu#546] opened 2018-03-29 02:47 UTC
This probably isn't a bug, just some behavior I wasn't expecting due to my very limited understanding of NLU. Hopefully, this can either be fixed or otherwise you can help point me towards a workaround.

First I'll describe how to reproduce the behavior I'm talking about, and then explain what I was expecting.

Steps to reproduce:
1. Take the sample_dataset.json and the sample.py script as per the quickstart
2. Ensure it all runs normally. Your probability for `sampleGetWeather` should be about 65%
3. In the sample_dataset.py, add the following intent:
```json
    "sampleGetWeatherClone": {
      "utterances": [
        {
          "data": [
            {
              "text": "What will be the weather in "
            },
            {
              "text": "London",
              "entity": "location",
              "slot_name": "weatherLocation"
            },
            {
              "text": ", "
            },
            {
              "text": "tomorrow morning",
              "entity": "snips/datetime",
              "slot_name": "weatherDate"
            },
            {
              "text": "?"
            }
          ]
        }
      ]
    }
```
4.  In sample.py, update the parse line to include "sampleGetWeather" for the Intents parameter:
`parsing = nlu_engine.parse(text, "sampleGetWeather")`

What happens:
When you run the script, the match is `sampleGetWeather` with a probability of about 25%

What did I expect:
Since our search has narrowed to the scope of just the sampleGetWeather intent, I expected the probability to remain at around 65% rather than degrading due to the duplicate intent utterances

Is there any way I can achieve this behavior that I was expecting? Perhaps some workaround that I'm not considering?

**Comment by warent** [comment] 2018-03-29 03:18
I've just considered a workaround for this, which is to create different training data sets and contextually switch between them.

**Comment by adrienball** [comment] 2018-03-30 08:32
Hi @warent ,

I guess the `intents` parameter of the parsing API is not very clear at the moment. What it does is more filtering the classification results:
- If you pass a list of intents, then once the classification is made, the winning intent will be the most likely intents which appears in the provided intents list (hence sometimes not the number one intent overall)
- If you pass a single intent, the same logic applies and in this case the specified intent will always be returned so it will force the classification to chose this intent

In both cases, the probabilities computation is computed as it would be without this intents filter.
In your example, the problem is that you added an intent which is very close to an existing one, hence their classification probabilities are split.
If you try to add another intent with very different utterances, you'll see that the probability will stay very close to the one you had before (~65%).

I hope this will help 😉

**Comment by adrienball** [comment] 2018-05-04 09:59
@warent 
Quick follow up: here is the [PR](https://github.com/snipsco/snips-nlu/pull/585) that should improve the classification probabilities in general, you can check the notes for more details.

You can directly test it for your use case by installing snips-nlu through: 
`pip install git+https://github.com/snipsco/snips-nlu.git@improvement/probabilities-calibration`
Alternatively you can wait for it to be integrated in the next release.

I'd be interested to have your feedback if you test it 😉

**Comment by adrienball** [comment] 2018-07-08 12:29
Hey @warent , I'm closing this issue as it should be fixed now.
Feel free to reopen it if you still have some troubles.
Cheers

**Closed by adrienball** 2018-07-08 12:29 UTC
