### ISSUE TITLE
while generating dataset from yaml to json

### ISSUE THREAD

**Issue by cahuja1992** [snipsco/snips-nlu#775] opened 2019-03-28 07:06 UTC
If utterance starts with the entity it fails to parse it
language: de
example:
  - [sequence] (erstes) audio abspielen
  - [sequence] (zweite) songs abspielen
  - [sequence] (dritte) audiospur abspielen
  - wiedergabe von [sequence] (vierter) musik aus der playlist
  - [sequence] (ersten) titel aus der liste abspielen

**Comment by adrienball** [comment] 2019-03-28 08:42
Hi @cahuja1992,
This is a duplicate of https://github.com/snipsco/snips-nlu/issues/719
The documentation mentions this specific issue --> https://snips-nlu.readthedocs.io/en/latest/dataset.html#intent

TL;DR --> You must put such sentences between double quotes.

**Closed by adrienball** 2019-03-28 08:42 UTC
