### ISSUE TITLE
Unable to install on MacOS, Linux

### ISSUE THREAD

**Issue by PenetratingShot** [snipsco/snips-nlu#785] opened 2019-04-18 13:38 UTC
So I installed snips-nlu on my MacBook, which is running 10.14.5 (Mojave). It used to work, but then for some reason it doesn't recognize the snips-nlu module anymore. I haven't changed anything. So then I redid `pip install snips-nlu`, which didn't help. It's worth noting that when the module did work, the `snips-nlu` command didn't work. When the `snips-nlu` command started working, it was when python wasn't recognizing the module.

So then I moved to Ubuntu 16. It happened there too. `pip install snips-nlu` just returns `no module named snips_nlu`. Same thing happens when running `python -m snips_nlu` or `import snips_nlu`.

I've done this across three different ubuntu instances and it hasn't working a single time.

**Comment by adrienball** [comment] 2019-04-18 13:53
Hi @PenetratingShot ,
This is likely to be due to a wrong python environment.
Are your running in a virtual environment?
In order to troubleshoot this, and if it is not already the case, I recommend you to use virtualenv and run the following commands:
```bash
> virtualenv -p </path/to/python/binary> venv
> . venv/bin/activate
> pip install snips-nlu
> python -c "import snips_nlu;"
```

If you have no error here, which is expected, then it means that there is something wrong with your python setup. Typically, perhaps the `pip` binary which you are using doesn't correspond to the `python` in your `PATH`. You can check this by running:

```bash
> pip --version
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
> python --version
Python 3.6.5
```

If you do have an error after running the commands mentioned at the beginning, then there is an issue on our side and we will investigate. But as far as I can tell, this hasn't been reported by anyone and I can't reproduce on my machine (MacOS Mojave 10.14.4).

I hope this helps,
Best

**Comment by PenetratingShot** [comment] 2019-04-23 13:30
Ok thank you. I will try this when I get home today. Though I will note that running `python --version` returns python 2.6 and pip is installed for python 2.6, but running `python3 --version` returns python version 3. Is there any way that I can update `python` and `pip` to their respective latest versions?

Thanks

**Comment by adrienball** [comment] 2019-04-23 13:38
The best way to ensure that `python` and `pip` are using the version you want is to work inside a [virtual environment](https://virtualenv.pypa.io/en/latest/).

**Comment by adrienball** [comment] 2019-07-04 10:04
@PenetratingShot I'm closing this issue, assuming it was a python environment issue.
Feel free to re-open if you still have the issue.

**Closed by adrienball** 2019-07-04 10:04 UTC
